### ISSUE TITLE
Error after building. Amy idea how to resolve this? Thanks. 

### ISSUE THREAD

**Issue by michaelchi08** [DaniGarciaLopez/ros2_explorer#1]
**ros2 launch explorer_bringup map10.launch.py**
[INFO] [launch]: All log files can be found below /home/chi/.ros/log/2021-07-05-21-25-01-637335-chi-49624
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:274> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 49, in get_package_prefix
    content, package_prefix = get_resource('packages', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/resources.py", line 48, in get_resource
    raise LookupError(
LookupError: Could not find the resource 'turtlebot3_gazebo' of type 'packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/chi/turtlebot3_ws/install/explorer_bringup/share/explorer_bringup/map10.launch.py", line 38, in generate_launch_description
    gazebo_launch_file_dir = os.path.join(get_package_share_directory('turtlebot3_gazebo'), 'launch')
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 69, in get_package_share_directory
    return os.path.join(get_package_prefix(package_name), 'share', package_name)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_index_python/packages.py", line 51, in get_package_prefix
    raise PackageNotFoundError(
ament_index_python.packages.PackageNotFoundError: "package 'turtlebot3_gazebo' not found, searching: ['/home/chi/turtlebot3_ws/install/turtlebot3', '/home/chi/turtlebot3_ws/install/turtlebot3_teleop', '/home/chi/turtlebot3_ws/install/turtlebot3_bringup', '/home/chi/turtlebot3_ws/install/turtlebot3_node', '/home/chi/turtlebot3_ws/install/turtlebot3_navigation2', '/home/chi/turtlebot3_ws/install/turtlebot3_example', '/home/chi/turtlebot3_ws/install/turtlebot3_description', '/home/chi/turtlebot3_ws/install/turtlebot3_cartographer', '/home/chi/turtlebot3_ws/install/explorer_wanderer', '/home/chi/turtlebot3_ws/install/explorer_navigation2', '/home/chi/turtlebot3_ws/install/explorer_map_utils', '/home/chi/turtlebot3_ws/install/explorer_interfaces', '/home/chi/turtlebot3_ws/install/explorer_gazebo', '/home/chi/turtlebot3_ws/install/explorer_cartographer', '/home/chi/turtlebot3_ws/install/explorer_bringup', '/opt/ros/foxy']"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 276, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 296, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 125, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: "package 'turtlebot3_gazebo' not found, searching: ['/home/chi/turtlebot3_ws/install/turtlebot3', '/home/chi/turtlebot3_ws/install/turtlebot3_teleop', '/home/chi/turtlebot3_ws/install/turtlebot3_bringup', '/home/chi/turtlebot3_ws/install/turtlebot3_node', '/home/chi/turtlebot3_ws/install/turtlebot3_navigation2', '/home/chi/turtlebot3_ws/install/turtlebot3_example', '/home/chi/turtlebot3_ws/install/turtlebot3_description', '/home/chi/turtlebot3_ws/install/turtlebot3_cartographer', '/home/chi/turtlebot3_ws/install/explorer_wanderer', '/home/chi/turtlebot3_ws/install/explorer_navigation2', '/home/chi/turtlebot3_ws/install/explorer_map_utils', '/home/chi/turtlebot3_ws/install/explorer_interfaces', '/home/chi/turtlebot3_ws/install/explorer_gazebo', '/home/chi/turtlebot3_ws/install/explorer_cartographer', '/home/chi/turtlebot3_ws/install/explorer_bringup', '/opt/ros/foxy']"

**Comment by DaniGarciaLopez** [comment]
Hi Michael. 

It cannot find `turtlebot_gazebo` package. Verify you installed it correctly. It's located [in this repo](https://github.com/ROBOTIS-GIT/turtlebot3_simulations).
